# Data Analysis

In [1]:
import pandas as pd
import numpy as np
import xgboost as xgb
import matplotlib.pyplot as plt
import seaborn as sns

/Users/seandiehl/opt/anaconda3/envs/thesis-env/lib/python3.9/site-packages/xgboost/compat.py:36: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  from pandas import MultiIndex, Int64Index

In [6]:
pd.set_option('display.max_columns', None)

df = pd.read_csv('/Users/seandiehl/Desktop/PBP-1819.csv')
df.head()

,X1,GAME_ID,PLAYER1_ID,PLAYER1_NAME,PLAYER1_TEAM_ID,PLAYER2_ID,PLAYER2_NAME,PLAYER3_ID,PLAYER3_NAME,TIME,ASSIST_PLAYER_ID,ASSIST_COUNT,BLOCK_PLAYER_ID,BLOCK_COUNT,REBOUND_PLAYER_ID,REBOUND_TEAM,REBOUND_OFFENSIVE_COUNT,REBOUND_DEFENSIVE_COUNT,FREE_THROW_PLAYER_ID,FREE_THROW_NUM,FREE_THROW_TOTAL,FREE_THROW_MADE,SHOT_PLAYER_ID,FT_POINTS_SCORED,FG_POINTS_SCORED,TOTAL_POINTS,SHOT_MADE,STEAL_PLAYER_ID,STEAL_COUNT,HOME_PLAYER_ID_1,HOME_PLAYER_ID_2,HOME_PLAYER_ID_3,HOME_PLAYER_ID_4,HOME_PLAYER_ID_5,AWAY_PLAYER_ID_1,AWAY_PLAYER_ID_2,AWAY_PLAYER_ID_3,AWAY_PLAYER_ID_4,AWAY_PLAYER_ID_5,HOME_PLAYER_ID_1_PLAY_TIME,HOME_PLAYER_ID_2_PLAY_TIME,HOME_PLAYER_ID_3_PLAY_TIME,HOME_PLAYER_ID_4_PLAY_TIME,HOME_PLAYER_ID_5_PLAY_TIME,AWAY_PLAYER_ID_1_PLAY_TIME,AWAY_PLAYER_ID_2_PLAY_TIME,AWAY_PLAYER_ID_3_PLAY_TIME,AWAY_PLAYER_ID_4_PLAY_TIME,AWAY_PLAYER_ID_5_PLAY_TIME
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0.0,21801052.0,0.0,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,202681.0,203935.0,201143.0,202694.0,1628369.0,1627750.0,203914.0,203999.0,200794.0,203115.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1.0,21801052.0,201143.0,Al Horford,1.610613e+09,203999.0,Nikola Jokic,200794.0,Paul Millsap,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,202681.0,203935.0,201143.0,202694.0,1628369.0,1627750.0,203914.0,203999.0,200794.0,203115.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,2.0,21801052.0,200794.0,Paul Millsap,1.610613e+09,0.0,NaN,0.0,NaN,19.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,200794.0,0,NaN,NaN,False,NaN,NaN,202681.0,203935.0,201143.0,202694.0,1628369.0,1627750.0,203914.0,203999.0,200794.0,203115.0,19.0,19.0,19.0,19.0,19.0,19.0,19.0,19.0,19.0,19.0
4,3.0,21801052.0,1628369.0,Jayson Tatum,1.610613e+09,0.0,NaN,0.0,NaN,21.0,NaN,NaN,NaN,NaN,1628369.0,NaN,0.0,1.0,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,202681.0,203935.0,201143.0,202694.0,1628369.0,1627750.0,203914.0,203999.0,200794.0,203115.0,21.0,21.0,21.0,21.0,21.0,21.0,21.0,21.0,21.0,21.0

In [7]:
projs = pd.read_csv('/Users/seandiehl/Desktop/projections-per-sec1819.csv')
projs.head()

,Unnamed: 0,Rk,Player,Type,FG,FGA,3P,3PA,FT,FTA,ORB,TRB,AST,STL,BLK,TOV,PF,PTS,FG%,3P%,FT%,PlayerID,Name,Person_ID
0,0,1,√Ålex Abrines\abrinal01,Projected,0.001944,0.004722,0.001296,0.003287,0.000694,0.000787,0.000370,0.001713,0.000602,0.000556,0.000139,0.000463,0.001759,0.005787,0.407,0.385,0.852,abrinal01,Alex Abrines,203518
1,2,2,Quincy Acy\acyqu01,Projected,0.001806,0.004676,0.001111,0.003102,0.000787,0.000972,0.000556,0.003194,0.000741,0.000417,0.000370,0.000741,0.001806,0.005509,0.389,0.358,0.786,acyqu01,Quincy Acy,203112
2,4,3,Steven Adams\adamsst01,Projected,0.002824,0.004676,0.000046,0.000093,0.001065,0.001852,0.002269,0.004491,0.000648,0.000602,0.000556,0.000880,0.001435,0.006806,0.609,0.327,0.588,adamsst01,Steven Adams,203500
3,6,4,Bam Adebayo\adebaba01,Projected,0.002269,0.004352,0.000093,0.000278,0.001574,0.002130,0.001389,0.004583,0.001296,0.000417,0.000509,0.000787,0.001620,0.006157,0.518,0.282,0.735,adebaba01,Bam Adebayo,1628389
4,8,5,LaMarcus Aldridge\aldrila01,Projected,0.004120,0.008333,0.000185,0.000556,0.001944,0.002361,0.001435,0.004028,0.001019,0.000324,0.000602,0.000741,0.001111,0.010370,0.495,0.317,0.829,aldrila01,LaMarcus Aldridge,200746